import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import ts from "typescript";

const ROOT_DIR = process.cwd();
const DIST_DIR = path.join(ROOT_DIR, "dist");
const SEO_CONFIG_PATH = path.join(ROOT_DIR, "src", "config", "seo.ts");
const SITE_URL = (process.env.VITE_SITE_URL || "https://theo-guerin.fr").replace(/\/+$/, "");
const PERSON_ID = `${SITE_URL}/#person`;
const DISTINCT_PAGE_ROUTES = new Set(["/", "/about", "/experience", "/project", "/contact", "/cv"]);
const ROBOTS_TXT_PATH = path.join(DIST_DIR, "robots.txt");
const MARKDOWN_RESOURCE_FILES = [
  "llms.txt",
  "llms-fr.txt",
  "llms-en.txt",
  "profile.md",
  "projects.md",
  "experience.md",
  "contact.md",
];

// Load the same TypeScript SEO config used by the app and the prerender generator.
function loadTsModule(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  const output = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  }).outputText;

  const sandbox = {
    exports: {},
    module: { exports: {} },
  };
  sandbox.module.exports = sandbox.exports;
  vm.runInNewContext(output, sandbox, { filename: filePath });
  return sandbox.exports;
}

// Recreate the exact route set generated by scripts/seo-static.mjs.
function getGeneratedRoutes(seoConfig) {
  const routePaths = Object.entries(seoConfig.ROUTE_SEO)
    .filter(([, config]) => !config.noindex)
    .map(([pathname]) => pathname);

  return [
    ...new Set([
      ...routePaths,
      ...seoConfig.SUPPORTED_LOCALES.flatMap((locale) =>
        routePaths.map((pathname) => seoConfig.getLocalizedPath(locale, pathname)),
      ),
    ]),
  ];
}

// Resolve the primary generated HTML file for a public route without trailing slash.
function htmlPath(routePath) {
  if (routePath === "/") {
    return path.join(DIST_DIR, "index.html");
  }

  return path.join(DIST_DIR, `${routePath.replace(/^\//, "")}.html`);
}

// Resolve the trailing-slash index file generated for static hosts that prefer directory indexes.
function trailingSlashHtmlPath(routePath) {
  if (routePath === "/") {
    return path.join(DIST_DIR, "index.html");
  }

  return path.join(DIST_DIR, routePath.replace(/^\//, ""), "index.html");
}

// Extract human-readable body text to detect empty or shell-only prerenders.
function textContent(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// Read the first document title from a generated HTML file.
function getTitle(html) {
  return html.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim() || "";
}

// Read the html lang value that crawlers receive before JavaScript runs.
function getHtmlLang(html) {
  return html.match(/<html\s+[^>]*lang=["']([^"']+)["']/i)?.[1]?.trim() || "";
}

// Read the route meta description from generated HTML.
function getMetaDescription(html) {
  return html.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["'][^>]*>/i)?.[1]?.trim() || "";
}

// Read the canonical URL from generated HTML.
function getCanonical(html) {
  return html.match(/<link\s+rel=["']canonical["']\s+href=["']([^"']+)["'][^>]*>/i)?.[1]?.trim() || "";
}

// Read the first H1 visible in prerendered content.
function getH1(html) {
  return html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]?.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim() || "";
}

// Collect hreflang alternates from generated HTML.
function getHreflangs(html) {
  return [...html.matchAll(/<link\s+rel=["']alternate["'][^>]*href=["']([^"']+)["'][^>]*hreflang=["']([^"']+)["'][^>]*>/gi)]
    .map((match) => ({ href: match[1], hrefLang: match[2] }));
}

// Parse every JSON-LD block and fail on invalid structured data.
function getStructuredData(html) {
  return [...html.matchAll(/<script\s+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].map((match) => {
    try {
      return JSON.parse(match[1]);
    } catch (error) {
      throw new Error(`JSON-LD invalide: ${error.message}`);
    }
  });
}

// Flatten Schema.org @graph blocks so assertions can search entities directly.
function flattenGraph(jsonLdBlocks) {
  return jsonLdBlocks.flatMap((block) => {
    if (Array.isArray(block?.["@graph"])) {
      return block["@graph"];
    }

    return [block];
  });
}

// Add a human-readable error when a condition is not met.
function assert(condition, message, errors) {
  if (!condition) {
    errors.push(message);
  }
}

// Keep robots.txt friendly to strict parsers such as Lighthouse.
function validateRobotsTxt(errors) {
  assert(fs.existsSync(ROBOTS_TXT_PATH), "robots.txt: fichier manquant dans dist", errors);
  if (!fs.existsSync(ROBOTS_TXT_PATH)) {
    return;
  }

  const bytes = fs.readFileSync(ROBOTS_TXT_PATH);
  const contents = bytes.toString("utf8");
  const hasUtf8Bom = bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf;

  assert(!hasUtf8Bom, "robots.txt: BOM UTF-8 interdit avant User-agent", errors);
  assert(contents.startsWith("User-agent: *"), "robots.txt: doit commencer par User-agent: *", errors);
  assert(contents.includes(`Sitemap: ${SITE_URL}/sitemap.xml`), "robots.txt: sitemap canonique manquant", errors);
}

// llms.txt and companion Markdown files need a real Markdown heading and no BOM.
function validateMarkdownResources(errors) {
  for (const markdownFile of MARKDOWN_RESOURCE_FILES) {
    const filePath = path.join(DIST_DIR, markdownFile);
    assert(fs.existsSync(filePath), `${markdownFile}: fichier Markdown/LLM manquant dans dist`, errors);
    if (!fs.existsSync(filePath)) {
      continue;
    }

    const bytes = fs.readFileSync(filePath);
    const contents = bytes.toString("utf8");
    const hasUtf8Bom = bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf;

    assert(!hasUtf8Bom, `${markdownFile}: BOM UTF-8 interdit avant le H1`, errors);
    assert(contents.startsWith("# "), `${markdownFile}: doit commencer par un H1 Markdown`, errors);
    assert(contents.trim().length > 120, `${markdownFile}: contenu trop court`, errors);
  }
}

// Compute the canonical URL expected for a generated route.
function expectedCanonical(routePath, seoConfig) {
  const localized = seoConfig.splitLocalizedPath(routePath);
  const pathname = seoConfig.normalizePath(localized.pathname);
  const locale = localized.locale ?? seoConfig.DEFAULT_LOCALE;
  return `${SITE_URL}${seoConfig.getLocalizedPath(locale, pathname)}`;
}

// Compute the expected HTML language, including content fallbacks for legal pages.
function expectedHtmlLang(routePath, seoConfig) {
  const localized = seoConfig.splitLocalizedPath(routePath);
  const pathname = seoConfig.normalizePath(localized.pathname);
  const locale = localized.locale ?? seoConfig.DEFAULT_LOCALE;
  return seoConfig.getHtmlLang(seoConfig.getContentLocale(locale, pathname));
}

// Ensure every localized route advertises the complete and correct hreflang cluster.
function validateHreflangs({ routePath, html, seoConfig, errors }) {
  const localized = seoConfig.splitLocalizedPath(routePath);
  const pathname = seoConfig.normalizePath(localized.pathname);
  const alternates = getHreflangs(html);

  for (const locale of seoConfig.SUPPORTED_LOCALES) {
    const expectedHrefLang = seoConfig.getHtmlLang(locale);
    const expectedHref = `${SITE_URL}${seoConfig.getLocalizedPath(locale, pathname)}`;
    const match = alternates.find((alternate) => alternate.hrefLang === expectedHrefLang);
    assert(match, `${routePath}: hreflang ${expectedHrefLang} manquant`, errors);
    assert(match?.href === expectedHref, `${routePath}: hreflang ${expectedHrefLang} pointe vers ${match?.href || "rien"} au lieu de ${expectedHref}`, errors);
  }

  const xDefault = alternates.find((alternate) => alternate.hrefLang === "x-default");
  const expectedDefault = `${SITE_URL}${seoConfig.getLocalizedPath(seoConfig.DEFAULT_LOCALE, pathname)}`;
  assert(xDefault, `${routePath}: hreflang x-default manquant`, errors);
  assert(xDefault?.href === expectedDefault, `${routePath}: x-default pointe vers ${xDefault?.href || "rien"} au lieu de ${expectedDefault}`, errors);
}

// Validate every generated indexable route plus the LLM Markdown resources.
function main() {
  const seoConfig = loadTsModule(SEO_CONFIG_PATH);
  const routes = getGeneratedRoutes(seoConfig);
  const errors = [];
  const titles = new Map();
  const descriptions = new Map();

  validateRobotsTxt(errors);
  validateMarkdownResources(errors);

  for (const routePath of routes) {
    const filePath = htmlPath(routePath);
    assert(fs.existsSync(filePath), `${routePath}: HTML prérendu manquant (${filePath})`, errors);
    const trailingPath = trailingSlashHtmlPath(routePath);
    assert(fs.existsSync(trailingPath), `${routePath}/: HTML prérendu trailing slash manquant (${trailingPath})`, errors);
    if (!fs.existsSync(filePath)) {
      continue;
    }

    const html = fs.readFileSync(filePath, "utf8");
    const title = getTitle(html);
    const description = getMetaDescription(html);
    const canonical = getCanonical(html);
    const htmlLang = getHtmlLang(html);
    const h1 = getH1(html);
    const bodyText = textContent(html);
    const expectedCanonicalUrl = expectedCanonical(routePath, seoConfig);
    const expectedLang = expectedHtmlLang(routePath, seoConfig);
    let jsonLdBlocks = [];

    try {
      jsonLdBlocks = getStructuredData(html);
    } catch (error) {
      errors.push(`${routePath}: ${error.message}`);
    }

    const graph = flattenGraph(jsonLdBlocks);
    const person = graph.find((node) => node?.["@type"] === "Person");
    const webPage = graph.find((node) => String(node?.["@id"] || "").endsWith("#webpage"));

    assert(title, `${routePath}: <title> manquant`, errors);
    assert(description, `${routePath}: meta description manquante`, errors);
    assert(canonical, `${routePath}: canonical manquant`, errors);
    assert(canonical === expectedCanonicalUrl, `${routePath}: canonical ${canonical} au lieu de ${expectedCanonicalUrl}`, errors);
    assert(htmlLang === expectedLang, `${routePath}: html lang ${htmlLang || "absent"} au lieu de ${expectedLang}`, errors);
    assert(h1, `${routePath}: H1 manquant`, errors);
    assert(bodyText.length > 450, `${routePath}: HTML prérendu trop pauvre (${bodyText.length} caractères)`, errors);
    assert(jsonLdBlocks.length > 0, `${routePath}: JSON-LD manquant`, errors);
    assert(person?.["@id"] === PERSON_ID, `${routePath}: Person @id incorrect ou absent`, errors);
    assert(webPage?.url === canonical, `${routePath}: WebPage JSON-LD url incorrecte`, errors);
    assert(webPage?.inLanguage === expectedLang, `${routePath}: WebPage JSON-LD inLanguage incorrect`, errors);
    validateHreflangs({ routePath, html, seoConfig, errors });

    if (DISTINCT_PAGE_ROUTES.has(routePath)) {
      if (titles.has(title)) {
        errors.push(`${routePath}: title dupliqué avec ${titles.get(title)} (${title})`);
      } else {
        titles.set(title, routePath);
      }

      if (descriptions.has(description)) {
        errors.push(`${routePath}: description dupliquée avec ${descriptions.get(description)}`);
      } else {
        descriptions.set(description, routePath);
      }
    }
  }

  if (errors.length > 0) {
    console.error(errors.map((error) => `- ${error}`).join("\n"));
    process.exit(1);
  }

  console.log(`SEO check passed for ${routes.length} generated prerendered routes.`);
}

main();
